### ISSUE TITLE
publish new images after recent PRs are merged and tested

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#1012]
### Follow up to https://github.com/nextcloud/all-in-one/issues/948
(add the most recent ticket for a new release here)

### Tested:
(add PRs below that are potentially breaking and need to be well tested)
- [x] https://github.com/nextcloud/all-in-one/pull/995
- [x] https://github.com/nextcloud/all-in-one/pull/977
- [x] https://github.com/nextcloud/all-in-one/pull/989
- [x] https://github.com/nextcloud/all-in-one/pull/996
- [x] https://github.com/nextcloud/all-in-one/pull/997
- [x] https://github.com/nextcloud/all-in-one/pull/1006
- [x] https://github.com/nextcloud/all-in-one/pull/1007
- [x] https://github.com/nextcloud/all-in-one/pull/1019
- [x] https://github.com/nextcloud/all-in-one/commit/1411a0d8b1272595830f6dbf2535b92a8b787a8b (check how it looks) fixed with https://github.com/nextcloud/all-in-one/commit/b307c39f70df090be6352e9adf28e6ec36f64246
- [x] https://github.com/nextcloud/all-in-one/pull/1018
- [x] https://github.com/nextcloud/all-in-one/pull/1020

### Tasks to do for new release:
- [x] increase the version number in https://github.com/nextcloud/all-in-one/blob/main/php/templates/containers.twig#L19
- [x] build new images. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-build-new-containers
- [x] do a last smoke test using the develop channel (See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-test-things-correctly)
- [x] deploy from develop to beta. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-promote-builds-from-develop-to-beta
- [x] tag a new release here on github which fits the version number (and use vX.Y.Z as tag and title + `Beta`, use the autogenerated changelog) and make it a pre-release
- [x] rename `next` milestone to the same version number
- [x] create a new milestone that is called `next`
- [x] move all open issues/PRs to that new milestone
- [x] post in all issues and discussions that were fixed/implemented that this is now released with the new beta version and post how to switch to the beta channel (e.g. `This is now released with X.Y.Z Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel`)
- [x] wait a week and see if new bugs get reported (until 24.08.)
- [x] if not, publish to latest as describe below; if yes simply close this milestone and create a new one that includes the bugfixes and starts from the beginning of this guide
- [x] merge https://github.com/nextcloud/all-in-one/pull/1025
- [x] deploy from beta to latest. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-promote-builds-from-beta-to-latest
- [x] change the pre-release to be a stable release and remove `Beta` from the title 
- [x] close the old milestone
