### ISSUE TITLE
publish new images after recent PRs are merged and tested

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#1041]
### Follow up to https://github.com/nextcloud/all-in-one/issues/1012
(add the most recent ticket for a new release here)

### Tested:
(add PRs below that are potentially breaking and need to be well tested)
- [x] https://github.com/nextcloud/all-in-one/commit/ae29ce409e0afad7babeac5f9b16d848c9dd4783
- [x] https://github.com/nextcloud/all-in-one/pull/1024 (fixed with https://github.com/nextcloud/all-in-one/commit/20892c2d40c9bc9633ffaeffeb1c076ef8cf1ff5)
- [x] https://github.com/nextcloud/all-in-one/pull/1026 (fixed with https://github.com/nextcloud/all-in-one/commit/096be7107a4a4e708e120d10ddd00db75eff0532)
- [x] https://github.com/nextcloud/all-in-one/pull/1058 (fixed with https://github.com/nextcloud/all-in-one/pull/1060 and https://github.com/nextcloud/all-in-one/pull/1059)
- [x] https://github.com/nextcloud/all-in-one/pull/1028
- [x] https://github.com/nextcloud/all-in-one/pull/1029 (fixed with https://github.com/nextcloud/all-in-one/commit/2e1e53e9d3ce11d0b390c9fe2977d6b00746666b  and https://github.com/nextcloud/all-in-one/commit/7b4876c681abdbd6e828bbcd7c82b68b47e0a6f9)
- [x] https://github.com/nextcloud/all-in-one/pull/1030 (Currently not working due to https://github.com/nextcloud/all-in-one/pull/1030#issuecomment-1223110690 will be postponed in https://github.com/nextcloud/all-in-one/issues/1048; fixed with https://github.com/nextcloud/all-in-one/commit/c90ee1c4dba4a8fdaa232ba8f86cd0e2fda00fb2)
- [x] https://github.com/nextcloud/all-in-one/pull/1035
- [x] https://github.com/nextcloud/all-in-one/pull/1042
- [x] https://github.com/nextcloud/all-in-one/commit/09003fcce19a871797ee6629aa69b6b6a3b9ca19
- [x] https://github.com/nextcloud/all-in-one/pull/1044 (fixed with https://github.com/nextcloud/all-in-one/pull/1065)
- [x] https://github.com/nextcloud/all-in-one/pull/1046 (fixed with https://github.com/nextcloud/all-in-one/commit/40b2e014fb8d5031cf42cc23e7fcf6c646bcf7d3 and https://github.com/nextcloud/all-in-one/commit/b22c239998fc010beefd8e0ff4b4e5b229532c43)
- [x] https://github.com/nextcloud/all-in-one/pull/1050

### Tasks to do for new release:
- [x] increase the version number in https://github.com/nextcloud/all-in-one/blob/main/php/templates/containers.twig#L19
- [x] build new images. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-build-new-containers
- [x] do a last smoke test using the develop channel (See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-test-things-correctly)
- [x] deploy from develop to beta. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-promote-builds-from-develop-to-beta
- [x] tag a new release here on github which fits the version number (and use vX.Y.Z as tag and title + `Beta`, use the autogenerated changelog) and make it a pre-release
- [x] rename `next` milestone to the same version number
- [x] create a new milestone that is called `next`
- [x] move all open issues/PRs to that new milestone
- [x] post in all issues and discussions that were fixed/implemented that this is now released with the new beta version and post how to switch to the beta channel (e.g. `This is now released with X.Y.Z Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel`)
- [x] wait a week and see if new bugs get reported and don't merge any PR into the main branch of this repo in the meantime! til 02.09.
- [ ] if not, publish to latest as describe below; if yes simply close this milestone and create a new one that includes the bugfixes and starts from the beginning of this guide
- [ ] merge https://github.com/nextcloud/all-in-one/pull/1045
- [ ] deploy from beta to latest. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-promote-builds-from-beta-to-latest
- [ ] change the pre-release to be a stable release and remove `Beta` from the title 
- [ ] close the old milestone
