### ISSUE TITLE
publish new images after recent PRs are merged and tested

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#1279]
### Follow up to https://github.com/nextcloud/all-in-one/issues/1192
(add the most recent ticket for a new release here)

### Tested:
(add PRs below that are potentially breaking and need to be well tested)
- [x] https://github.com/nextcloud/all-in-one/pull/1249 (fixed with https://github.com/nextcloud/all-in-one/commit/6458bf661314fae49f255506254fa6f17712c1a5 and https://github.com/nextcloud/all-in-one/commit/a03fad2c335348af7ea3cec1845e613a9ef0dbf7)
- [x] https://github.com/nextcloud/all-in-one/pull/1274
- [x] https://github.com/nextcloud/all-in-one/pull/1275
- [x] https://github.com/nextcloud/all-in-one/pull/1305
- [x] https://github.com/nextcloud/all-in-one/commit/e5fce3eb890659b1033a6afa36f8a4a146edf7a5
- [x] https://github.com/nextcloud/all-in-one/pull/1302
- [x] https://github.com/nextcloud/all-in-one/pull/1307
- [x] https://github.com/nextcloud/all-in-one/pull/1325
- [x] https://github.com/nextcloud/all-in-one/pull/1326
- [x] ~~https://github.com/nextcloud/all-in-one/pull/1329~~ no idea

### Tasks to do for new release:
- [x] increase the version number in https://github.com/nextcloud/all-in-one/blob/main/php/templates/containers.twig#L19
- [x] build new images. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-build-new-containers
- [x] do a last smoke test using the develop channel (See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-test-things-correctly)
- [x] deploy from develop to beta. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-promote-builds-from-develop-to-beta
- [x] tag a new release here on github which fits the version number (and use vX.Y.Z as tag and title + `Beta`, use the autogenerated changelog) and make it a pre-release
- [x] rename `next` milestone to the same version number
- [x] create a new milestone that is called `next`
- [x] move all open issues/PRs to that new milestone
- [x] post in all issues and discussions that were fixed/implemented that this is now released with the new beta version and post how to switch to the beta channel (e.g. `This is now released with X.Y.Z Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel`)
- [x] wait a week and see if new bugs get reported and don't merge any PR into the main branch of this repo in the meantime! (until 03.11.)
- [ ] if not, publish to latest as describe below; if yes simply close this milestone and create a new one that includes the bugfixes and starts from the beginning of this guide
- [ ] deploy from beta to latest. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-promote-builds-from-beta-to-latest
- [ ] change the pre-release to be a stable release and remove `Beta` from the title 
- [ ] close the old milestone
