### ISSUE TITLE
publish new images after recent PRs are merged and tested

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#133]
Follow up to #99

tested:
- [x] #59
- [x] #94
- [x] https://github.com/nextcloud/all-in-one/pull/136
- [x] https://github.com/nextcloud/all-in-one/pull/137
- [x] https://github.com/nextcloud/all-in-one/pull/138 (See if it sucessfully builds)
- [x] #142 (see if it sucessfully builds)
- [x] #148
- [x] #153 (test if caddy still works on amd64
- [ ] #151 (test the whole aio interface as much as possible)
- [x] #158
- [x] #162

When done, publish affected images to latest

- [x] apache
- [x] nextcloud
- [x] collabora (on 21.01.)
- [x] all-in-one
    - [x] increase the version number in https://github.com/nextcloud/all-in-one/blob/main/php/templates/containers.twig#L19
    - [x] deploy from develop to latest
    - [x] tag a new release here on github which fits the version number (and use vX.Y.Z as tag and title, use the autogenerated changelog)
    - [x] rename `next` milestone to the same version number
    - [x] create a new milestone that is called `next`
    - [x] move all open issues/PRs to that new milestone
    - [x] close the old milestone

Info:
- Sync repo to nextcloud-releases and build containers via https://github.com/nextcloud-releases/all-in-one/actions/workflows/repo-sync.yml
