### ISSUE TITLE
publish new images after recent PRs are merged and tested

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#1526]
### Follow up to https://github.com/nextcloud/all-in-one/issues/1476 
(add the most recent ticket for a new release here)

(note: last backup with 24.0.8 is from 15.12. 04:00) 

### Tested:
(add PRs below that are potentially breaking and need to be well tested)
- [x] https://github.com/nextcloud/all-in-one/pull/1432
- [x] https://github.com/nextcloud/all-in-one/pull/1495 
- [x] https://github.com/nextcloud/all-in-one/pull/1496 
- [x] https://github.com/nextcloud/all-in-one/pull/1497
- [x] https://github.com/nextcloud/all-in-one/pull/1498
- [x] https://github.com/nextcloud/all-in-one/pull/1513
- [x] https://github.com/nextcloud/all-in-one/pull/1506
- [x] https://github.com/nextcloud/all-in-one/commit/0b961c9dfc6c7f90f75c3ade89ec30e8492063f9
- [x] https://github.com/nextcloud/all-in-one/pull/1532
- [x] https://github.com/nextcloud/all-in-one/pull/1533
- [x] https://github.com/nextcloud/all-in-one/pull/1541
- [x] https://github.com/nextcloud/all-in-one/pull/1539
- [x] AIO-app works
- [x] fts works
- [x] clamav works
- [x] imaginary works
- [x] collabora works
- [x] ~~backgroundjobs works (theming produces error log)~~ not fixable here
- [x] ~~nothing in logs (theming produces error log)~~ not fixable here
- [x] migration work
- [x] onlyoffice works
- [x] theming update 

### Tasks to do for new release:
- [x] increase the version number in https://github.com/nextcloud/all-in-one/blob/main/php/templates/containers.twig#L19
- [x] build new images. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-build-new-containers
- [x] do a last smoke test using the develop channel (See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-test-things-correctly)
- [x] deploy from develop to beta. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-promote-builds-from-develop-to-beta 
- [x] tag a new release here on github which fits the version number (and use vX.Y.Z as tag and title + `Beta`, use the autogenerated changelog) and make it a pre-release
- [x] rename `next` milestone to the same version number
- [x] create a new milestone that is called `next`
- [x] move all open issues/PRs to that new milestone
- [x] post in all issues and discussions that were fixed/implemented that this is now released with the new beta version and post how to switch to the beta channel (e.g. `This is now released with X.Y.Z Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel`)
- [ ] wait two weeks and see if new bugs get reported and don't merge any PR into the main branch of this repo in the meantime! (until 31.12.)
- [ ] potential blockker: https://github.com/nextcloud/all-in-one/issues/1547
- [ ] if not, publish to latest as describe below; if yes simply close this milestone and create a new one that includes the bugfixes and starts from the beginning of this guide
- [ ] deploy from beta to latest. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-promote-builds-from-beta-to-latest
- [ ] Close https://github.com/nextcloud/all-in-one/issues/1280
- [ ] Merge https://github.com/nextcloud/all-in-one/pull/1527
- [ ] change the pre-release to be a stable and the latest release and remove `Beta` from the title 
- [ ] close the old milestone
