### ISSUE TITLE
upgrade Nextcloud container to php 8.1 with Nc26

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#1782]
- [ ] needs update to nc26

## TODO
- [ ] upgrade to php 8.1 and alpine 3.17 (can use 3.18 if 3.18.1 should be out by then)
- [x] ~~check if openssl3.0 needs workaround https://github.com/nextcloud/server/pull/36173~~ shouldnt be after with the mentioned PR
- [ ] test
- [ ] also update dependency link (3.16) in the readme then

**Comment by st3iny** [comment]
> check if openssl3.0 needs workaround

I can confirm that you will need it. I'm using OpenSSL 3 on one of my dev machines and server-side encryption completely breaks.

**Comment by szaimen** [comment]
Thanks for the update! Is this still needed after https://github.com/nextcloud/server/pull/36173 ?

**Comment by st3iny** [comment]
It will work an all OpenSSL version with this PR applied.

**Comment by szaimen** [comment]
Great! 🚀

**Comment by szaimen** [comment]
This is now released with v6.0.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
