### ISSUE TITLE
publish new images after recent PRs are merged and tested

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#1829]
### Follow up to https://github.com/nextcloud/all-in-one/issues/1730
(add the most recent ticket for a new release here)

### Tested:
(add PRs below that are potentially breaking and need to be well tested)
- [x] https://github.com/nextcloud/all-in-one/pull/1823
- [x] https://github.com/nextcloud/all-in-one/pull/1817
- [x] https://github.com/nextcloud/all-in-one/pull/1816
- [x] https://github.com/nextcloud/all-in-one/pull/1785 
- [x] https://github.com/nextcloud/all-in-one/pull/1584
- [x] https://github.com/nextcloud/all-in-one/pull/1577 (fixed with https://github.com/nextcloud/all-in-one/commit/3102dbfaebd1fb329fa1db00bbbed0183d502fe1)
- [x] https://github.com/nextcloud/all-in-one/pull/1573 
- [x] https://github.com/nextcloud/all-in-one/pull/1835 (fixed with https://github.com/nextcloud/all-in-one/commit/7a126a96d9c38da42d60f23025d4141286827c3d)
- [x] https://github.com/nextcloud/all-in-one/pull/1840 
- [x] https://github.com/nextcloud/all-in-one/pull/1845
- [x] https://github.com/nextcloud/all-in-one/pull/1869
- [x] https://github.com/nextcloud/all-in-one/commit/8824a8471b58111781302203de37f7f2ed2dabda
- [x] https://github.com/nextcloud/all-in-one/pull/1879
- [x] https://github.com/nextcloud/all-in-one/pull/1887
- [x] https://github.com/nextcloud/all-in-one/pull/1890 (fixed with https://github.com/nextcloud/all-in-one/commit/d7b0d07c71fae047c26f796ca6d0ea495864d189)
- [x] https://github.com/nextcloud/all-in-one/pull/1889 
- [x] https://github.com/nextcloud/all-in-one/pull/1900

### Tasks to do for new release:
- [x] make sure to merge any `Helm Chart Updates` PR before continuing with the list below.
- [x] increase the version number in https://github.com/nextcloud/all-in-one/blob/main/php/templates/containers.twig#L19
- [x] build new images. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-build-new-containers
- [x] do a last smoke test using the develop channel (See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-test-things-correctly)
- [x] merge https://github.com/nextcloud-releases/all-in-one/pull/31
- [x] deploy from develop to beta. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-promote-builds-from-develop-to-beta
- [x] ~~check if beta was pushed correctly (beta multiarch, beta-arm64 and check if `application/vnd.docker.container.image.v1+json` is still used~~ (reverted in https://github.com/nextcloud-releases/all-in-one/pull/32)
- [x] tag a new release here on github which fits the version number (and use vX.Y.Z as tag and title + `Beta`, use the autogenerated changelog) and make it a pre-release
- [x] rename `next` milestone to the same version number
- [x] create a new milestone that is called `next`
- [x] move all open issues/PRs to that new milestone
- [x] post in all issues and discussions that were fixed/implemented that this is now released with the new beta version and post how to switch to the beta channel (e.g. `This is now released with X.Y.Z Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel`)
- [ ] wait a week and see if new bugs get reported and don't merge any PR into the main branch of this repo in the meantime! (until 16.02.)
- [x] if not, publish to latest as describe below; if yes simply close this milestone and create a new one that includes the bugfixes and starts from the beginning of this guide
- [ ] deploy from beta to latest. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-promote-builds-from-beta-to-latest
- [ ] change documentation for https://github.com/nextcloud/all-in-one/discussions/490
- [ ] Merge the automated `YAML updates` PR if there should  be one
- [ ] change the pre-release to be a stable and the latest release and remove `Beta` from the title 
- [ ] close the old milestone
