### ISSUE TITLE
Update to nc26

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#1846]
## Tasks

TODO:
- [x] ~~Wait for at least 26.0.1~~ we release with 26.0.0 (Andy)

Apps not compatible:
- [ ] increase aio version to 26
- [x] antivirus
- [ ] FTS
- [ ] [other bundled apps](https://cloud.nextcloud.com/f/4473673)
- [ ] [further apps](https://help.nextcloud.com/t/any-apps-not-compatible-with-nextcloud-26/155950)

Issues:
- [x] https://github.com/nextcloud/server/issues/36419
- [x] https://github.com/nextcloud/files_pdfviewer/issues/701
- [x] https://github.com/nextcloud/server/issues/36502
- [x] https://github.com/nextcloud/server/issues/36510
- [x] https://github.com/nextcloud/server/issues/36540
- [x] https://github.com/nextcloud/server/issues/36541
- [x] https://github.com/nextcloud/groupfolders/issues/2264
- [ ] https://github.com/nextcloud/server/issues/37473
- [ ] https://github.com/nextcloud/photos/issues/1733
- [x] https://github.com/nextcloud/server/issues/36787
- [ ] the update to nc26 resets the theming again?
- [x] https://github.com/nextcloud/server/issues/37277
- [x] https://github.com/nextcloud/server/issues/37329
- [x] https://github.com/nextcloud/server/issues/37379
- [x] https://github.com/nextcloud/server/issues/37383
- [x] https://github.com/nextcloud/richdocuments/issues/2873
- [ ] https://github.com/nextcloud/server/issues/37407
- [x] https://github.com/nextcloud/server/issues/37396
- [ ] https://github.com/nextcloud/server/issues/37414
- [x] https://github.com/nextcloud/user_saml/issues/709
- [ ] https://github.com/nextcloud/server/issues/37461
- [ ] https://github.com/nextcloud/server/issues/37527
- [ ] https://github.com/nextcloud/photos/pull/1692
- [ ] [further issues](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3A26-feedback)
- [ ] https://github.com/nextcloud/text/issues?q=is%3Aopen+is%3Aissue+label%3A%2226+feedback%22

Test:
- [ ] check if all included features work
- [ ] check admin overview
- [ ] check each other overview
- [ ] check if nextcloud-aio app works
- [ ] remove potentially added note in the aio interface about nextcloud 26 by changing newMajorVersion to ''
- [ ] ...

**Comment by reos-rcrozier** [comment]
I have themed nextcloud, and updating to 26 did NOT reset any theming settings for me.

**Comment by szaimen** [comment]
A feature is now implemented that allows to install Nc26 during the initial installation with v4.8.0 Beta. Also a hint is added directly to the AIO interface that explains how to upgrade to Nc26 now.

**Comment by AndyScherzinger** [comment]
@ArtificialOwl please ping @szaimen as soon as you are done with the FTS publishings for v26 - thanks in advance!

**Comment by FlattusBlastus** [comment]
> > Currently mainly FTS is still missing...
> 
> Planned for this week

You are late, good sir.

**Comment by szaimen** [comment]
4.8.1 stable was released
