### ISSUE TITLE
Migrate as many containers as possible to alpine for decreased size and increased security

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#185]
- [x] ~~apache~~ out of scope for now since we would need to implement our own a2enmod, etc.
- [x] ~~borgbackup~~ probably out of scope as well since we would run into issues with the already existing cache volume
- [x] ~~collabora~~ the image is provided by upstream so not much we can do here
- [x] domaincheck already on alpine
- [x] ~~mastercontainer~~ probably out of scope for now too since we would need to implement our own a2enmod, etc.
- [x] nextcloud should be doable, probably the most improvements in size and security #204
- [x] postgresql should be doable as well #202
- [x] redis should be doable as well #203
- [x] ~~talk~~ out of scope since our dependencies rely on ubuntu
- [x] watchtower should be doable (just reuse the existing image or modify it slightly) #201

**Comment by szaimen** [comment]
apache, borgbackup, mastercontainer can problably get migrated to debian-slim though.

**Comment by szaimen** [comment]
everything done
