### ISSUE TITLE
publish new images after recent PRs are merged and tested

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#2335]
### Follow up to https://github.com/nextcloud/all-in-one/issues/2263
(add the most recent ticket for a new release here)

### Tested:
(add PRs below that are potentially breaking and need to be well tested)
- [x] https://github.com/nextcloud/all-in-one/pull/2288
    - [x] bug: heic, heif and pdf previews currently dont work anymore
    - [x] (if it works, delete the imaginary workflow in the releases repo)
    - [x] also delete the repo on docker hub then
- [x] https://github.com/nextcloud/all-in-one/pull/2296 (fixed formatting with https://github.com/nextcloud/all-in-one/commit/a145bf33a321c4b69e21bb25f5dcb4fa6029006c)
- [x] https://github.com/nextcloud/all-in-one/pull/2301
- [x] https://github.com/nextcloud/all-in-one/pull/2302
- [x] https://github.com/nextcloud/all-in-one/pull/2307
- [x] https://github.com/nextcloud/all-in-one/pull/2328
- [x] https://github.com/nextcloud/all-in-one/pull/2331
- [x] https://github.com/nextcloud/all-in-one/pull/2334
- [x] https://github.com/nextcloud/all-in-one/pull/2343

### Tasks to do for new release:
- [x] make sure to merge any `Helm Chart Updates` PR before continuing with the list below (https://github.com/nextcloud/all-in-one/pulls)
- [x] increase the version number in https://github.com/nextcloud/all-in-one/blob/main/php/templates/containers.twig#L19
- [x] build new images. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-build-new-containers
- [x] do a last smoke test using the develop channel (See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-test-things-correctly)
- [x] deploy from develop to beta. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-promote-builds-from-develop-to-beta
- [x] tag a new release here on github which fits the version number (and use vX.Y.Z as tag and title + `Beta`, use the autogenerated changelog) and make it a pre release
- [x] rename `next` milestone to the same version number
- [x] create a new milestone that is called `next`
- [x] move all open issues/PRs to that new milestone
- [x] post in all issues and discussions that were fixed/implemented that this is now released with the new beta version and post how to switch to the beta channel (e.g. `This is now released with X.Y.Z Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel`)
- [x] wait a week and see if new bugs get reported and don't merge any PR into the main branch of this repo in the meantime! (until 22.04.) but release earlier if FTS should be ready for Nc26 by then.
- [x] if not, publish to latest as describe below; if yes simply close this milestone and create a new one that includes the bugfixes and starts from the beginning of this guide
- [x] deploy from beta to latest. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-promote-builds-from-beta-to-latest
- [x] Merge the automated `YAML updates` PR if there should  be one (https://github.com/nextcloud/all-in-one/pulls)
- [x] change the pre-release to be a stable and the latest release and remove `Beta` from the title 
- [x] close the old milestone
