### ISSUE TITLE
tasks for nc26

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#2336]
## Tasks

TODO:
- [x] Wait for at least 26.0.1
- [x] wait for 26.0.2

Apps not compatible:
- [x] increase aio version to 26
- [x] antivirus
- [x] FTS
- [x] [other bundled apps](https://cloud.nextcloud.com/f/4473673)
- [x] [further apps](https://help.nextcloud.com/t/any-apps-not-compatible-with-nextcloud-26/155950)

Issues:
- [x] https://github.com/nextcloud/server/issues/36419
- [x] https://github.com/nextcloud/files_pdfviewer/issues/701
- [x] https://github.com/nextcloud/server/issues/36502
- [x] https://github.com/nextcloud/server/issues/36510
- [x] https://github.com/nextcloud/server/issues/36540
- [x] https://github.com/nextcloud/server/issues/36541
- [x] https://github.com/nextcloud/groupfolders/issues/2264
- [x] https://github.com/nextcloud/server/issues/37473
- [ ] https://github.com/nextcloud/photos/issues/1733
- [x] https://github.com/nextcloud/server/issues/36787
- [ ] the update to nc26 resets the theming again?
- [x] https://github.com/nextcloud/server/issues/37277
- [x] https://github.com/nextcloud/server/issues/37329
- [x] https://github.com/nextcloud/server/issues/37379
- [x] https://github.com/nextcloud/server/issues/37383
- [x] https://github.com/nextcloud/richdocuments/issues/2873
- [x] https://github.com/nextcloud/server/issues/37407
- [x] https://github.com/nextcloud/server/issues/37396
- [x] https://github.com/nextcloud/server/issues/37414
- [x] https://github.com/nextcloud/user_saml/issues/709
- [ ] https://github.com/nextcloud/server/issues/37461
- [ ] https://github.com/nextcloud/server/issues/37527
- [x] https://github.com/nextcloud/photos/pull/1692
- [x] https://github.com/nextcloud/photos/issues/1753
- [ ] [further issues](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3A26-feedback)
- [ ] https://github.com/nextcloud/text/issues?q=is%3Aopen+is%3Aissue+label%3A%2226+feedback%22

Test:
- [ ] check if all included features work
    - [x] talk
    - [x] collabora
    - [x] imaginary
    - [x] fts
    - [x] clamav
    - [x] notify push
- [x] check admin overview
- [x] check each other overview
- [x] check if nextcloud-aio app works
- [x] remove potentially added note in the aio interface about nextcloud 26 by changing newMajorVersion to ''
- [ ] ...

**Comment by kaulex99** [comment]
Are there any updates on Nextcloud AIO 26 release date?

**Comment by szaimen** [comment]
Basically we are now only waiting for 26.0.2 to release and then work on the remaining points above. Until then see https://github.com/nextcloud/all-in-one/discussions/2208

**Comment by kaulex99** [comment]
@szaimen Thank you for the fast answer and the link!

**Comment by GUNT0815** [comment]
Nextcloud 26.0.2 is there https://github.com/nextcloud/server/milestone/221
