### ISSUE TITLE
publish new images after recent PRs are merged and tested

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#2407]
### Follow up to https://github.com/nextcloud/all-in-one/issues/2335
(add the most recent ticket for a new release here)

### Tested:
(add PRs below that are potentially breaking and need to be well tested)
- [x] https://github.com/nextcloud/all-in-one/pull/2368
- [x] https://github.com/nextcloud/all-in-one/pull/2358
- [x] https://github.com/nextcloud/all-in-one/pull/2357
- [x] https://github.com/nextcloud/all-in-one/pull/2401
- [x] https://github.com/nextcloud/all-in-one/pull/2383 (test with new instance)
- [x] https://github.com/nextcloud/all-in-one/pull/2384
- [x] https://github.com/nextcloud/all-in-one/pull/2385
- [x] https://github.com/nextcloud/all-in-one/pull/2396 (test with new intance)
- [x] https://github.com/nextcloud/all-in-one/pull/2397
- [x] https://github.com/nextcloud/all-in-one/pull/2406 (improved with https://github.com/nextcloud/all-in-one/commit/48746c24debbdf0934ff08441bed2a6331d93f2c) (also test with new instance)
- [x] https://github.com/nextcloud/all-in-one/pull/2389 (fixed with https://github.com/nextcloud/all-in-one/commit/c76e0aa1c10d5d733ffcdd468df78e32ffc8218b) (also test with new instance)
- [x] https://github.com/nextcloud/all-in-one/commit/359d43d3dd744ba3873198d8591f7da542735c06
- [x] https://github.com/nextcloud/all-in-one/pull/2413
- [x] https://github.com/nextcloud/all-in-one/commit/6debc29685b3d0bd666d3980c7abae6ec72b144c
- [x] https://github.com/nextcloud/all-in-one/pull/2417
- [x] https://github.com/nextcloud/all-in-one/pull/2418
- [x] https://github.com/nextcloud/all-in-one/commit/d8719e810c66e0ca5b5e7e815bd07a3d75d7d8ac

### Tasks to do for new release:
- [x] make sure to merge any `Helm Chart Updates` PR before continuing with the list below (https://github.com/nextcloud/all-in-one/pulls)
- [x] increase the version number in https://github.com/nextcloud/all-in-one/blob/main/php/templates/containers.twig#L19
- [x] build new images. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-build-new-containers
- [x] do a last smoke test using the develop channel (See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-test-things-correctly)
- [x] deploy from develop to beta. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-promote-builds-from-develop-to-beta
- [x] tag a new release here on github which fits the version number (and use vX.Y.Z as tag and title + `Beta`, use the autogenerated changelog) and make it a pre release
- [x] rename `next` milestone to the same version number
- [x] create a new milestone that is called `next`
- [x] move all open issues/PRs to that new milestone
- [x] post in all issues and discussions that were fixed/implemented that this is now released with the new beta version and post how to switch to the beta channel (e.g. `This is now released with X.Y.Z Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel`)
- [x] wait a week and see if new bugs get reported and don't merge any PR into the main branch of this repo in the meantime! (Until 02.05.)
- [x] if not, publish to latest as describe below; if yes simply close this milestone and create a new one that includes the bugfixes and starts from the beginning of this guide
- [x] deploy from beta to latest. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-promote-builds-from-beta-to-latest
- [x] Merge the automated `YAML updates` PR if there should  be one (https://github.com/nextcloud/all-in-one/pulls)
- [x] change the pre-release to be a stable and the latest release and remove `Beta` from the title 
- [x] close the old milestone
