### ISSUE TITLE
Update nc 27

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#2686]
## Tasks

TODO:
- [x] Wait for at least 27.0.1

Apps not compatible:
- [x] increase aio version to 27
- [x] antivirus (see https://github.com/nextcloud/files_fulltextsearch/pull/232: needs a release now)
- [x] FTS
- [x] deck
- [x] [other bundled apps](https://cloud.nextcloud.com/f/4473673)
- [x] [further apps](https://help.nextcloud.com/t/apps-not-compatible-with-nc-27-yet/163634)

Issues:
- [x] https://github.com/nextcloud/server/pull/38420
- [x] https://github.com/nextcloud/server/pull/38361
- [x] https://github.com/nextcloud/server/pull/38474
- [x] https://github.com/nextcloud/files_fulltextsearch/issues/221
- [x] https://github.com/nextcloud/photos/issues/1885
- [x] https://github.com/nextcloud/groupfolders/issues/2429
- [ ] https://github.com/nextcloud/groupfolders/issues
- [ ] https://github.com/nextcloud/server/issues/38797
- [ ] https://github.com/nextcloud/server/issues/38874
- [x] https://github.com/nextcloud/text/pull/4553
- [x] https://github.com/nextcloud/server/pull/39005
- [x] https://github.com/nextcloud/server/issues/38902
- [x] https://github.com/nextcloud/server/issues/38503
- [x] https://github.com/nextcloud/activity/issues/1199
- [x] https://github.com/nextcloud/files_fulltextsearch/pull/232
- [x] https://github.com/nextcloud/server/pull/39028
- [ ] https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue++label%3A27-feedback+

Test:
- [x] check if all included features work
- [x] check admin overview
- [x] check each other overview
- [x] check if nextcloud-aio app works
- [x] remove potentially added note in the aio interface about nextcloud 27 by changing newMajorVersion to ''
- [ ] ...

**Comment by szaimen** [comment]
This is now released with v7.0.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
