### ISSUE TITLE
publish new images after recent PRs are merged and tested

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#2753]
### Follow up to https://github.com/nextcloud/all-in-one/issues/2747
(add the most recent ticket for a new release here)

### Tested:
(add PRs below that are potentially breaking and need to be well tested)
- [x] https://github.com/nextcloud/all-in-one/pull/2797
- [x] https://github.com/nextcloud/all-in-one/pull/2813
- [x] https://github.com/nextcloud/all-in-one/pull/2807
- [x] https://github.com/nextcloud/all-in-one/pull/2800
- [x] https://github.com/nextcloud/all-in-one/pull/2811 (fixed with https://github.com/nextcloud/all-in-one/commit/89b349574094290326d6ea31bfd7731ec7e17d82)
- [x] https://github.com/nextcloud/all-in-one/pull/2812
- [x] https://github.com/nextcloud/all-in-one/commit/997360da7f0605544439182acc9f6ea51aa00042
- [x] https://github.com/nextcloud/all-in-one/pull/2784
- [x] https://github.com/nextcloud/all-in-one/pull/2793
- [x] https://github.com/nextcloud/all-in-one/pull/2796
- [x] https://github.com/nextcloud/all-in-one/pull/2794
- [x] https://github.com/nextcloud/all-in-one/pull/2751 (test talk-recording with 26)
- [x] https://github.com/nextcloud/all-in-one/pull/2731
- [x] https://github.com/nextcloud/all-in-one/pull/2730
- [x] https://github.com/nextcloud/all-in-one/pull/2725 (test with backup from 2023-06-10 12:26:52 UTC)
- [x] https://github.com/nextcloud/all-in-one/pull/2709
- [x] https://github.com/nextcloud/all-in-one/pull/2708
- [x] https://github.com/nextcloud/all-in-one/pull/2707
- [x] https://github.com/nextcloud/all-in-one/pull/2783
- [x] https://github.com/nextcloud/all-in-one/pull/2706
- [x] https://github.com/nextcloud/all-in-one/pull/2703
- [x] https://github.com/nextcloud/all-in-one/pull/2701
- [x] https://github.com/nextcloud/all-in-one/pull/2698
- [x] https://github.com/nextcloud/all-in-one/pull/2697
- [x] https://github.com/nextcloud/all-in-one/commit/713d48eecd1494524951900de24589760375e105
- [x] https://github.com/nextcloud/all-in-one/pull/2768
    - [x] apache
    - [x] borg
    - [x] domaincheck
    - [x] imaginary
    - [x] nextcloud
    - [x] talk
    - [x] watchtower
- [x] https://github.com/nextcloud/all-in-one/pull/2762

### Tasks to do for new release:
- [x] make sure to merge any `Helm Chart Updates` PR before continuing with the list below (https://github.com/nextcloud/all-in-one/pulls)
- [x] increase the version number in https://github.com/nextcloud/all-in-one/blob/main/php/templates/containers.twig#L19
- [x] build new images. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-build-new-containers
- [x] do a last smoke test using the develop channel (See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-test-things-correctly)
- [x] deploy from develop to beta. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-promote-builds-from-develop-to-beta
- [x] tag a new release here on github which fits the version number (and use vX.Y.Z as tag and title + `Beta`, use the autogenerated changelog) and make it a pre release
- [x] rename `next` milestone to the same version number
- [x] create a new milestone that is called `next`
- [x] move all open issues/PRs to that new milestone
- [x] post in all issues and discussions that were fixed/implemented that this is now released with the new beta version and post how to switch to the beta channel (e.g. `This is now released with X.Y.Z Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel`)
- [x] wait a week and see if new bugs get reported and don't merge any PR into the main branch of this repo in the meantime! (until 26.6.)
- [ ] if not, publish to latest as describe below; if yes simply close this milestone and create a new one that includes the bugfixes and starts from the beginning of this guide
- [ ] deploy from beta to latest. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-promote-builds-from-beta-to-latest
- [ ] Merge the automated `YAML updates` PR if there should  be one (https://github.com/nextcloud/all-in-one/pulls)
- [ ] change the pre-release to be a stable and the latest release and remove `Beta` from the title (and adjust the changelog if multiple Beta version have been pushed in the meantime without a stable release - the changelog must include all changes since the latest stable release)
- [ ] close the old milestone
