### ISSUE TITLE
publish new images after recent PRs are merged and tested

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#3640]
### Follow up to https://github.com/nextcloud/all-in-one/issues/3615
(add the most recent ticket for a new release here)

### Tested:
(add PRs below that are potentially breaking and need to be well tested)
- [x] https://github.com/nextcloud/all-in-one/pull/3583
- [x] https://github.com/nextcloud/all-in-one/pull/3584
- [x] https://github.com/nextcloud/all-in-one/pull/3594
- [x] https://github.com/nextcloud/all-in-one/pull/3608
- [x] https://github.com/nextcloud/all-in-one/pull/3611
- [x] https://github.com/nextcloud/all-in-one/pull/3639
- [x] https://github.com/nextcloud/all-in-one/pull/3641
- [x] https://github.com/nextcloud/all-in-one/pull/3642
- [x] https://github.com/nextcloud/all-in-one/commit/c85bacc940b1efda905e760863bfe81e0668155f

### Tasks to do for new release:
- [x] make sure to merge any `Helm Chart Updates` PR before continuing with the list below (https://github.com/nextcloud/all-in-one/pulls)
- [x] increase the version number in https://github.com/nextcloud/all-in-one/blob/main/php/templates/containers.twig#L19
- [x] build new images. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-build-new-containers
- [x] do a last smoke test using the develop channel (See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-test-things-correctly)
- [x] deploy from develop to beta. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-promote-builds-from-develop-to-beta
- [x] tag a new release [here on github](https://github.com/nextcloud/all-in-one/releases/new) which fits the version number (and use vX.Y.Z as tag and title + `Beta`, use the autogenerated changelog. **Important:** also add the included Nextcloud version manually into the body of the release, e.g. `Nextcloud 26.0.2 is included but new instances can install Nextcloud 27 directly`) and make it a pre release
- [x] rename `next` milestone to the same version number
- [x] create a new milestone that is called `next`
- [x] move all open issues/PRs to that new milestone
- [x] post in all issues and discussions that were fixed/implemented that this is now released with the new beta version and post how to switch to the beta channel (e.g. `This is now released with X.Y.Z Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel`)
- [ ] wait a week and see if new bugs get reported and don't merge any PR into the main branch of this repo in the meantime! (until 16.11.)
- [ ] if not, publish to latest as describe below; if yes simply close this milestone and create a new one that includes the bugfixes and starts from the beginning of this guide
- [ ] deploy from beta to latest. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-promote-builds-from-beta-to-latest
- [ ] Merge the automated `YAML updates` PR if there should  be one (https://github.com/nextcloud/all-in-one/pulls)
- [ ] change the pre-release to be a stable and the latest release and remove `Beta` from the title (and adjust the changelog if multiple Beta version have been pushed in the meantime without a stable release - the changelog must include all changes since the latest stable release)
- [ ] close the old milestone

**Comment by szaimen** [comment]
I get these issues now:
```
{"reqId":"WJW3omCMEkbSeX6JFWv7","level":3,"time":"2023-11-02T18:50:46+00:00","remoteAddr":"89.245.208.119","user":"admin","app":"no app in context","method":"PUT","url":"/remote.php/webdav/test/Copy%20share%20link%20doesn't%20work%20through%20photo%20app.gif","message":"An exception occurred while executing a query: SQLSTATE[HY000]: General error: 7 FATAL:  terminating connection due to idle-session timeout\nserver closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36","version":"27.1.3.2","exception":{"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing a query: SQLSTATE[HY000]: General error: 7 FATAL:  terminating connection due to idle-session timeout\nserver closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.","Code":7,"Trace":[{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1814,"function":"convert","class":"Doctrine\\DBAL\\Driver\\API\\PostgreSQL\\ExceptionConverter","type":"->","args":[["Doctrine\\DBAL\\Driver\\PDO\\Exception"],["Doctrine\\DBAL\\Query"]]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1749,"function":"handleDriverException","class":"Doctrine\\DBAL\\Connection","type":"->","args":[["Doctrine\\DBAL\\Driver\\PDO\\Exception"],["Doctrine\\DBAL\\Query"]]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1055,"function":"convertExceptionDuringQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":[["Doctrine\\DBAL\\Driver\\PDO\\Exception"],"SELECT \"filecache\".\"fileid\", \"storage\", \"path\", \"path_hash\", \"filecache\".\"parent\", \"filecache\".\"name\", \"mimetype\", \"mimepart\", \"size\", \"mtime\", \"storage_mtime\", \"encrypted\", \"etag\", \"permissions\", \"checksum\", \"unencrypted_size\", \"metadata_etag\", \"creation_time\", \"upload_time\" FROM \"oc_filecache\" \"filecache\" LEFT JOIN \"oc_filecache_extended\" \"fe\" ON \"filecache\".\"fileid\" = \"fe\".\"fileid\" WHERE (\"storage\" = ?) AND (\"path_hash\" = ?)",[1,"22074748a026daa2820ba8c2b84b18f9"],[1,2]]},{"file":"/var/www/html/lib/private/DB/Connection.php","line":262,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["SELECT \"filecache\".\"fileid\", \"storage\", \"path\", \"path_hash\", \"filecache\".\"parent\", \"filecache\".\"name\", \"mimetype\", \"mimepart\", \"size\", \"mtime\", \"storage_mtime\", \"encrypted\", \"etag\", \"permissions\", \"checksum\", \"unencrypted_size\", \"metadata_etag\", \"creation_time\", \"upload_time\" FROM \"oc_filecache\" \"filecache\" LEFT JOIN \"oc_filecache_extended\" \"fe\" ON \"filecache\".\"fileid\" = \"fe\".\"fileid\" WHERE (\"storage\" = ?) AND (\"path_hash\" = ?)",[1,"22074748a026daa2820ba8c2b84b18f9"],[1,2],"*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":345,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["SELECT \"filecache\".\"fileid\", \"storage\", \"path\", \"path_hash\", \"filecache\".\"parent\", \"filecache\".\"name\", \"mimetype\", \"mimepart\", \"size\", \"mtime\", \"storage_mtime\", \"encrypted\", \"etag\", \"permissions\", \"checksum\", \"unencrypted_size\", \"metadata_etag\", \"creation_time\", \"upload_time\" FROM \"oc_filecache\" \"filecache\" LEFT JOIN \"oc_filecache_extended\" \"fe\" ON \"filecache\".\"fileid\" = \"fe\".\"fileid\" WHERE (\"storage\" = :dcValue1) AND (\"path_hash\" = :dcValue2)",[1,"22074748a026daa2820ba8c2b84b18f9"],[1,2]]},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":280,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/lib/private/Files/Cache/Cache.php","line":168,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/lib/private/Files/Cache/HomeCache.php","line":57,"function":"get","class":"OC\\Files\\Cache\\Cache","type":"->","args":["files/test/Copy share link doesn't work through photo app.gif"]},{"file":"/var/www/html/lib/private/Files/View.php","line":1324,"function":"get","class":"OC\\Files\\Cache\\HomeCache","type":"->","args":["files/test/Copy share link doesn't work through photo app.gif"]},{"file":"/var/www/html/lib/private/Files/View.php","line":1374,"function":"getCacheEntry","class":"OC\\Files\\View","type":"->","args":[["OCA\\Files_Trashbin\\Storage","*** sensitive parameters replaced ***",["OC\\Files\\Cache\\Scanner"],"*** sensitive parameters replaced ***","*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"],"files/test/Copy share link doesn't work through photo app.gif","/test/Copy share link doesn't work through photo app.gif"]},{"file":"/var/www/html/lib/private/Files/Node/HookConnector.php","line":230,"function":"getFileInfo","class":"OC\\Files\\View","type":"->","args":["/admin/files/test/Copy share link doesn't work through photo app.gif"]},{"file":"/var/www/html/lib/private/Files/Node/HookConnector.php","line":125,"function":"getNodeForPath","class":"OC\\Files\\Node\\HookConnector","type":"->","args":["/test/Copy share link doesn't work through photo app.gif"]},{"file":"/var/www/html/lib/private/legacy/OC_Hook.php","line":105,"function":"create","class":"OC\\Files\\Node\\HookConnector","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/File.php","line":439,"function":"emit","class":"OC_Hook","type":"::","args":["OC_Filesystem","create","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/File.php","line":323,"function":"emitPreHooks","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[false]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/Directory.php","line":149,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1098,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":504,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:PUT",[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v1/webdav.php","line":85,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/remote.php","line":172,"args":["/var/www/html/apps/dav/appinfo/v1/webdav.php"],"function":"require_once"}],"File":"/var/www/html/3rdparty/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php","Line":91,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDO\\Exception","Message":"SQLSTATE[HY000]: General error: 7 FATAL:  terminating connection due to idle-session timeout\nserver closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.","Code":7,"Trace":[{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":103,"function":"new","class":"Doctrine\\DBAL\\Driver\\PDO\\Exception","type":"::","args":[["PDOException",["HY000",7,"FATAL:  terminating connection due to idle-session timeout\nserver closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request."]]]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1045,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->","args":[]},{"file":"/var/www/html/lib/private/DB/Connection.php","line":262,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["SELECT \"filecache\".\"fileid\", \"storage\", \"path\", \"path_hash\", \"filecache\".\"parent\", \"filecache\".\"name\", \"mimetype\", \"mimepart\", \"size\", \"mtime\", \"storage_mtime\", \"encrypted\", \"etag\", \"permissions\", \"checksum\", \"unencrypted_size\", \"metadata_etag\", \"creation_time\", \"upload_time\" FROM \"oc_filecache\" \"filecache\" LEFT JOIN \"oc_filecache_extended\" \"fe\" ON \"filecache\".\"fileid\" = \"fe\".\"fileid\" WHERE (\"storage\" = ?) AND (\"path_hash\" = ?)",[1,"22074748a026daa2820ba8c2b84b18f9"],[1,2],"*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":345,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["SELECT \"filecache\".\"fileid\", \"storage\", \"path\", \"path_hash\", \"filecache\".\"parent\", \"filecache\".\"name\", \"mimetype\", \"mimepart\", \"size\", \"mtime\", \"storage_mtime\", \"encrypted\", \"etag\", \"permissions\", \"checksum\", \"unencrypted_size\", \"metadata_etag\", \"creation_time\", \"upload_time\" FROM \"oc_filecache\" \"filecache\" LEFT JOIN \"oc_filecache_extended\" \"fe\" ON \"filecache\".\"fileid\" = \"fe\".\"fileid\" WHERE (\"storage\" = :dcValue1) AND (\"path_hash\" = :dcValue2)",[1,"22074748a026daa2820ba8c2b84b18f9"],[1,2]]},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":280,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/lib/private/Files/Cache/Cache.php","line":168,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/lib/private/Files/Cache/HomeCache.php","line":57,"function":"get","class":"OC\\Files\\Cache\\Cache","type":"->","args":["files/test/Copy share link doesn't work through photo app.gif"]},{"file":"/var/www/html/lib/private/Files/View.php","line":1324,"function":"get","class":"OC\\Files\\Cache\\HomeCache","type":"->","args":["files/test/Copy share link doesn't work through photo app.gif"]},{"file":"/var/www/html/lib/private/Files/View.php","line":1374,"function":"getCacheEntry","class":"OC\\Files\\View","type":"->","args":[["OCA\\Files_Trashbin\\Storage","*** sensitive parameters replaced ***",["OC\\Files\\Cache\\Scanner"],"*** sensitive parameters replaced ***","*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"],"files/test/Copy share link doesn't work through photo app.gif","/test/Copy share link doesn't work through photo app.gif"]},{"file":"/var/www/html/lib/private/Files/Node/HookConnector.php","line":230,"function":"getFileInfo","class":"OC\\Files\\View","type":"->","args":["/admin/files/test/Copy share link doesn't work through photo app.gif"]},{"file":"/var/www/html/lib/private/Files/Node/HookConnector.php","line":125,"function":"getNodeForPath","class":"OC\\Files\\Node\\HookConnector","type":"->","args":["/test/Copy share link doesn't work through photo app.gif"]},{"file":"/var/www/html/lib/private/legacy/OC_Hook.php","line":105,"function":"create","class":"OC\\Files\\Node\\HookConnector","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/File.php","line":439,"function":"emit","class":"OC_Hook","type":"::","args":["OC_Filesystem","create","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/File.php","line":323,"function":"emitPreHooks","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[false]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/Directory.php","line":149,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1098,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":504,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:PUT",[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v1/webdav.php","line":85,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/remote.php","line":172,"args":["/var/www/html/apps/dav/appinfo/v1/webdav.php"],"function":"require_once"}],"File":"/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php","Line":30,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[HY000]: General error: 7 FATAL:  terminating connection due to idle-session timeout\nserver closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.","Code":"HY000","Trace":[{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":101,"function":"execute","class":"PDOStatement","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1045,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->","args":[]},{"file":"/var/www/html/lib/private/DB/Connection.php","line":262,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["SELECT \"filecache\".\"fileid\", \"storage\", \"path\", \"path_hash\", \"filecache\".\"parent\", \"filecache\".\"name\", \"mimetype\", \"mimepart\", \"size\", \"mtime\", \"storage_mtime\", \"encrypted\", \"etag\", \"permissions\", \"checksum\", \"unencrypted_size\", \"metadata_etag\", \"creation_time\", \"upload_time\" FROM \"oc_filecache\" \"filecache\" LEFT JOIN \"oc_filecache_extended\" \"fe\" ON \"filecache\".\"fileid\" = \"fe\".\"fileid\" WHERE (\"storage\" = ?) AND (\"path_hash\" = ?)",[1,"22074748a026daa2820ba8c2b84b18f9"],[1,2],"*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":345,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["SELECT \"filecache\".\"fileid\", \"storage\", \"path\", \"path_hash\", \"filecache\".\"parent\", \"filecache\".\"name\", \"mimetype\", \"mimepart\", \"size\", \"mtime\", \"storage_mtime\", \"encrypted\", \"etag\", \"permissions\", \"checksum\", \"unencrypted_size\", \"metadata_etag\", \"creation_time\", \"upload_time\" FROM \"oc_filecache\" \"filecache\" LEFT JOIN \"oc_filecache_extended\" \"fe\" ON \"filecache\".\"fileid\" = \"fe\".\"fileid\" WHERE (\"storage\" = :dcValue1) AND (\"path_hash\" = :dcValue2)",[1,"22074748a026daa2820ba8c2b84b18f9"],[1,2]]},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":280,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/lib/private/Files/Cache/Cache.php","line":168,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/lib/private/Files/Cache/HomeCache.php","line":57,"function":"get","class":"OC\\Files\\Cache\\Cache","type":"->","args":["files/test/Copy share link doesn't work through photo app.gif"]},{"file":"/var/www/html/lib/private/Files/View.php","line":1324,"function":"get","class":"OC\\Files\\Cache\\HomeCache","type":"->","args":["files/test/Copy share link doesn't work through photo app.gif"]},{"file":"/var/www/html/lib/private/Files/View.php","line":1374,"function":"getCacheEntry","class":"OC\\Files\\View","type":"->","args":[["OCA\\Files_Trashbin\\Storage","*** sensitive parameters replaced ***",["OC\\Files\\Cache\\Scanner"],"*** sensitive parameters replaced ***","*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"],"files/test/Copy share link doesn't work through photo app.gif","/test/Copy share link doesn't work through photo app.gif"]},{"file":"/var/www/html/lib/private/Files/Node/HookConnector.php","line":230,"function":"getFileInfo","class":"OC\\Files\\View","type":"->","args":["/admin/files/test/Copy share link doesn't work through photo app.gif"]},{"file":"/var/www/html/lib/private/Files/Node/HookConnector.php","line":125,"function":"getNodeForPath","class":"OC\\Files\\Node\\HookConnector","type":"->","args":["/test/Copy share link doesn't work through photo app.gif"]},{"file":"/var/www/html/lib/private/legacy/OC_Hook.php","line":105,"function":"create","class":"OC\\Files\\Node\\HookConnector","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/File.php","line":439,"function":"emit","class":"OC_Hook","type":"::","args":["OC_Filesystem","create","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/File.php","line":323,"function":"emitPreHooks","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[false]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/Directory.php","line":149,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1098,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":504,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:PUT",[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v1/webdav.php","line":85,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/remote.php","line":172,"args":["/var/www/html/apps/dav/appinfo/v1/webdav.php"],"function":"require_once"}],"File":"/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","Line":101}},"CustomMessage":"--"},"id":"6543ef9de7a44"}
```
