### ISSUE TITLE
update to Nextcloud 28

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#3888]
## Tasks
 
TODO:
- [x] Wait for 28.0.3

Issues:
- [ ] https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue++label%3A28-feedback+
    - [x] https://github.com/nextcloud/server/issues/42489
    - [ ] https://github.com/nextcloud/server/issues/43423
    - [x] https://github.com/nextcloud/server/issues/43243
    - [ ] https://github.com/nextcloud/server/issues/43074
    - [x] https://github.com/nextcloud/server/issues/42200
    - [x] https://github.com/nextcloud/server/issues/42557
    - [x] https://github.com/nextcloud/server/issues/42510
    - [x] https://github.com/nextcloud/server/issues/42551
    - [x] https://github.com/nextcloud/server/issues/42493
    - [ ] https://github.com/nextcloud/server/issues/41408
    - [ ] https://github.com/nextcloud/server/issues/42157
    - [x] https://github.com/nextcloud/server/issues/42232 
    - [x] https://github.com/nextcloud/server/issues/42394
    - [ ] https://github.com/nextcloud/server/issues/42306
    - [x] https://github.com/nextcloud/server/issues/41253 https://github.com/nextcloud/server/pull/39506
    - [x] https://github.com/nextcloud/server/issues/42469
    - [x] https://github.com/nextcloud/server/issues/42308
    - [ ] https://github.com/nextcloud/server/issues/42501
    - [x] https://github.com/nextcloud/server/issues/41922
    - [ ] https://github.com/nextcloud/server/issues/42343
    - [x] https://github.com/nextcloud/server/issues/41456
    - [x] https://github.com/nextcloud/server/issues/42097
    - [x] https://github.com/nextcloud/server/issues/41260
    - [x] https://github.com/nextcloud/server/issues/42158
    - [x] https://github.com/nextcloud/server/issues/42620
    - [x] https://github.com/nextcloud/server/issues/42009

Apps not compatible:
- [x] increase aio version to 28 https://github.com/nextcloud/all-in-one/pull/4316
- [x] [other bundled apps](https://cloud.nextcloud.com/apps/tables/#/table/182)
- [ ] [further apps](https://help.nextcloud.com/t/apps-not-compatible-with-nc-28/176234)
    - [ ] files_downloadlimit
    - [ ] files_linkeditor
    - [x] memories
    - [ ] metadata
    - [x] music
    - [ ] facerecognition

Test:
- [x] test new instance?
- [x] check if all included features work
    - [x] ClamAV 
    - [x] Collabora
    - [x] Fulltextsearch should work with https://github.com/nextcloud-releases/fulltextsearch/releases/tag/28.0.1
    - [x] Imaginary (for previews of heic, heif, illustrator, pdf, svg, tiff and webp. Imaginary is currently [incompatible with server-side-encryption](https://github.com/nextcloud/server/issues/34262))
    - [x] talk recording
- [x] check admin overview
- [x] check each other overview
- [x] check if nextcloud-aio app works
- [x] remove potentially added note in the aio interface about nextcloud 28 by changing newMajorVersion to '' https://github.com/nextcloud/all-in-one/pull/4322
- [x] https://github.com/nextcloud/all-in-one/pull/4321
- [x] https://github.com/nextcloud/all-in-one/issues/2534
- [x] https://github.com/nextcloud/all-in-one/issues/2591
- [x] https://github.com/nextcloud/all-in-one/pull/3906
- [x] https://github.com/nextcloud/all-in-one/issues/3182
- [x] https://github.com/nextcloud/all-in-one/pull/4324
- [ ] ...

**Comment by EpicJosch** [comment]
Why is nothing happening here? 28.0.1 is alredy released

**Comment by szaimen** [comment]
> Why is nothing happening here? 28.0.1 is alredy released

You can upgrade at any time. See https://github.com/nextcloud/all-in-one/discussions/2692

**Comment by szaimen** [comment]
This is now released with v8.0.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
