### ISSUE TITLE
publish new images after recent PRs are merged and tested

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#4317]
### Follow up to  https://github.com/nextcloud/all-in-one/issues/4261
(add the most recent ticket for a new release here)

### Tested:
(add PRs below that are potentially breaking and need to be well tested)
- [x] https://github.com/nextcloud/all-in-one/pull/4316
- [ ] https://github.com/nextcloud/all-in-one/pull/4274
- [x] https://github.com/nextcloud/all-in-one/pull/4267
- [x] https://github.com/nextcloud/all-in-one/pull/3906 https://github.com/szaimen/aio-local-ai/pull/10#issuecomment-1847212762
- [x] https://github.com/nextcloud/all-in-one/pull/4318
- [x] https://github.com/nextcloud/all-in-one/pull/4320
- [x] https://github.com/nextcloud/all-in-one/pull/4321
- [x] https://github.com/nextcloud/all-in-one/pull/4322
- [x] https://github.com/nextcloud/all-in-one/pull/4324
- [x] https://github.com/nextcloud-releases/all-in-one/pull/45
- [x] https://github.com/nextcloud/all-in-one/pull/4323
- [x] https://github.com/nextcloud/all-in-one/pull/4325
- [x] https://github.com/nextcloud/all-in-one/pull/4326
- [x] https://github.com/nextcloud/all-in-one/pull/4343
- [x] https://github.com/nextcloud/all-in-one/commit/d55723dbea9a50fa6743fe6b6b540fecc26fce2d
- [x] Test: https://github.com/nextcloud/all-in-one/issues/3888#issue-2028951387

### Tasks to do for new release:
- [x] make sure to merge any `Helm Chart Updates` PR before continuing with the list below (https://github.com/nextcloud/all-in-one/pulls)
- [x] increase the version number in https://github.com/nextcloud/all-in-one/blob/main/php/templates/containers.twig#L19
- [x] build new images. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-build-new-containers https://github.com/nextcloud-releases/all-in-one/actions/runs/8202221000
- [x] do a last smoke test using the develop channel (See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-test-things-correctly)
- [x] deploy from develop to beta. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-promote-builds-from-develop-to-beta (check if https://github.com/nextcloud-releases/all-in-one/pull/45 works)
- [x] tag a new release [here on github](https://github.com/nextcloud/all-in-one/releases/new) which fits the version number (and use vX.Y.Z as tag and title + `Beta`, use the autogenerated changelog. **Important:** also add the included Nextcloud version manually into the body of the release, e.g. `Nextcloud 26.0.2 is included but new instances can install Nextcloud 27 directly`) and make it a pre release
- [x] rename `next` milestone to the same version number
- [x] create a new milestone that is called `next`
- [x] move all open issues/PRs to that new milestone
- [x] post in all issues and discussions that were fixed/implemented that this is now released with the new beta version and post how to switch to the beta channel (e.g. `This is now released with X.Y.Z Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel`)
- [x] wait two weeks and see if new bugs get reported and don't merge any PR into the main branch of this repo in the meantime! (until 21.03.)
- [x] if not, publish to latest as describe below; if yes simply close this milestone and create a new one that includes the bugfixes and starts from the beginning of this guide
- [x] deploy from beta to latest. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-promote-builds-from-beta-to-latest
- [x] Merge the automated `YAML updates` PR if there should  be one (https://github.com/nextcloud/all-in-one/pulls)
- [x] change the pre-release to be a stable and the latest release and remove `Beta` from the title (and adjust the changelog if multiple Beta version have been pushed in the meantime without a stable release - the changelog must include all changes since the latest stable release)
- [x] close the old milestone

**Comment by matteoipri** [comment]
I upgraded my test installation from 7.13.1 stable to 8.0.0 beta and everything seems to still work as expected.
The installation has been done towards the end of January directly to version 28.
This latest update brought me from N 28.0.1 to 28.0.3.

I want to migrate an existing installation done with nextcloud/docker (now at 28.0.3) to nextcloud/all-in-one. Is it safe to do it now with the beta channel, or should I pin my old installation at 28.0.3 and wait for the stable release of all-in-one v8.0.0?

**Comment by szaimen** [comment]
Following https://github.com/nextcloud/all-in-one/blob/main/migration.md should be possible from old docker v28.0.3 to AIO v8.0.0. The stable release is planned for 22.03. so you should have 11 days or longer to do the migration.
