### ISSUE TITLE
update to Nextcloud 29

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#4564]
## Tasks
 
TODO:
- [x] Wait for at least 29.0.1
- [x] Wait for https://github.com/nextcloud/all-in-one/issues/4653 to become stable
 
Issues:
- [x] https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue++label%3A29-feedback+
- [x] https://github.com/nextcloud/server/pull/45302
- [x] https://github.com/nextcloud/all-in-one/pull/4651
- [ ] https://github.com/nextcloud/server/issues/45257

Apps not compatible:
- [x] increase aio version to 29 https://github.com/nextcloud/all-in-one/pull/4770
- [x] [other bundled apps](https://cloud.nextcloud.com/apps/tables/#/table/182)
- [x] [further apps](https://help.nextcloud.com/t/apps-with-missing-nc29-support/186782)

Test:
- [x] test new instance?
- [x] check if all included features work
    - [x] ClamAV 
    - [x] Collabora
    - [x] Fulltextsearch 
    - [x] Imaginary (for previews of heic, heif, illustrator, pdf, svg, tiff and webp. Imaginary is currently [incompatible with server-side-encryption](https://github.com/nextcloud/server/issues/34262))
    - [x] Talk
    - [x] talk recording
    - [x] docker-socket-proxy
- [x] check admin overview
- [x] check each other overview
- [x] check if nextcloud-aio app works
- [x] remove potentially added note in the aio interface about nextcloud 28 by changing newMajorVersion to '' https://github.com/nextcloud/all-in-one/compare/enh/4564/hide-update-notice?expand=1
- [x] https://github.com/nextcloud/all-in-one/pull/4772
- [x] https://github.com/nextcloud/all-in-one/pull/4755
- [ ] ...
