### ISSUE TITLE
publish new images after recent PRs are merged and tested

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#4653]
### Follow up to https://github.com/nextcloud/all-in-one/issues/4575
(add the most recent ticket for a new release here)

### Tested:
(add PRs below that are potentially breaking and need to be well tested)
- [x] https://github.com/nextcloud/all-in-one/pull/4710
- [x] ~~wait for talk-recording-server update?~~ not for now
- [x] https://github.com/nextcloud/all-in-one/pull/4728
- [x] https://github.com/nextcloud/all-in-one/pull/4556
- [x] https://github.com/nextcloud/all-in-one/pull/4713
- [x] https://github.com/nextcloud/all-in-one/pull/4712
- [x] https://github.com/nextcloud/all-in-one/pull/4707
- [x] https://github.com/nextcloud/all-in-one/pull/4706
- [x] https://github.com/nextcloud/all-in-one/pull/4709
- [x] https://github.com/nextcloud/all-in-one/pull/4651 (check admin overview on existing install)
- [x] https://github.com/nextcloud/all-in-one/pull/4692
- [x] https://github.com/nextcloud/all-in-one/pull/4693 (test restore)
- [x] https://github.com/nextcloud/all-in-one/pull/4433 (test existing and new install)
- [x] https://github.com/nextcloud/all-in-one/pull/4685
- [x] https://github.com/nextcloud/all-in-one/pull/4687
- [x] https://github.com/nextcloud/all-in-one/pull/4588 (test per commit)
    - [x] [adjust link color](https://github.com/nextcloud/all-in-one/pull/4588/commits/9347144a1951407b6f8ee038de92c96a76b50270)
    - [x] [change Nextcloud AIO setup to All-in-One setup](https://github.com/nextcloud/all-in-one/pull/4588/commits/99567d687201229eb38a33209f6e0fd95d26998a)
    - [x] [add warning toe note down the password and make it big](https://github.com/nextcloud/all-in-one/pull/4588/commits/f8603b10fce895c7e487951b6986ce51bbfdf32f) fixed with https://github.com/nextcloud/all-in-one/commit/8fd457f62cfb2b4f871c9440802499b5fa1ad29b
    - [x] [change password to passphrase](https://github.com/nextcloud/all-in-one/pull/4588/commits/628abc02f6b04e634a86dd9bb9ac06d9c006ac9e)
    - [x] [adjust loader color to match nextcloud blue](https://github.com/nextcloud/all-in-one/pull/4588/commits/560dce906eecac422cbad61e8f7304d44d9b9aa8)
    - [x] [pre-fill the timezone](https://github.com/nextcloud/all-in-one/pull/4588/commits/26c042fd28fee57d18fbc13494b1f0936fd98e7a)
    - [x] [try to fix glitchy buttons](https://github.com/nextcloud/all-in-one/pull/4588/commits/5a826222d4a3de6c706b6f78413f06f13398e675)
    - [x] [add instructions how to inspect container logs](https://github.com/nextcloud/all-in-one/pull/4588/commits/63c667cac347619e2703d2cb301df84a6ad0c186) fixed with https://github.com/nextcloud/all-in-one/commit/8fd457f62cfb2b4f871c9440802499b5fa1ad29b
    - [x] [change wording](https://github.com/nextcloud/all-in-one/pull/4588/commits/000d881fc2ad1ece6a7dd0222e66e4e05be63c73)
    - [x] [adjust wording](https://github.com/nextcloud/all-in-one/pull/4588/commits/14153b424b11e52e376049724a498593d586b77a)
    - [x] [rename password to encryption password](https://github.com/nextcloud/all-in-one/pull/4588/commits/e78de8a113e04c4fe1e7ddf6a7d623486a375577)

### Tasks to do for new release:
- [x] make sure to merge any `Helm Chart Updates` PR before continuing with the list below (https://github.com/nextcloud/all-in-one/pulls)
- [x] increase the version number in https://github.com/nextcloud/all-in-one/blob/main/php/templates/containers.twig#L19
- [x] build new images. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-build-new-containers https://github.com/nextcloud-releases/all-in-one/actions/runs/9301603870
- [x] do a last smoke test using the develop channel (See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-test-things-correctly)
- [x] deploy from develop to beta. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-promote-builds-from-develop-to-beta
- [x] tag a new release [here on github](https://github.com/nextcloud/all-in-one/releases/new) which fits the version number (and use vX.Y.Z as tag and title + `Beta`, use the autogenerated changelog. **Important:** also add the included Nextcloud version manually into the body of the release, e.g. `Nextcloud 26.0.2 is included but new instances can install Nextcloud 27 directly`; also document this time that beta testers should test if talk calls still work for them) and make it a pre release
- [x] rename `next` milestone to the same version number
- [x] create a new milestone that is called `next`
- [x] move all open issues/PRs to that new milestone
- [x] post in all issues and discussions that were fixed/implemented that this is now released with the new beta version and post how to switch to the beta channel (e.g. `This is now released with X.Y.Z Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel`)
- [x] wait one week and see if new bugs get reported and don't merge any PR into the main branch of this repo in the meantime! (until 6.6.)
- [x] if not, publish to latest as describe below; if yes simply close this milestone and create a new one that includes the bugfixes and starts from the beginning of this guide
- [x] deploy from beta to latest. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-promote-builds-from-beta-to-latest
- [x] Merge the automated `YAML updates` PR if there should  be one (https://github.com/nextcloud/all-in-one/pulls)
- [x] change the pre-release to be a stable and the latest release and remove `Beta` from the title (and adjust the changelog if multiple Beta version have been pushed in the meantime without a stable release - the changelog must include all changes since the latest stable release)
- [x] remove changelog entry regarding beta testers
- [x] close the old milestone
