### ISSUE TITLE
publish new images after recent PRs are merged and tested

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#5086]
### Follow up to https://github.com/nextcloud/all-in-one/issues/5066
(add the most recent ticket for a new release here)

### Tested:
(add PRs below that are potentially breaking and need to be well tested)
- [x] https://github.com/nextcloud/all-in-one/pull/5016 (test upgrading from beta or develop to this one; should work with https://github.com/nextcloud/all-in-one/commit/c369b1f4aef4b14591ca743a4b03b030eda731cc)
- [x] https://github.com/nextcloud/all-in-one/pull/5202
- [x] https://github.com/nextcloud/all-in-one/pull/5192
- [x] https://github.com/nextcloud/all-in-one/pull/5175
- [x] https://github.com/nextcloud/all-in-one/pull/5181
- [x] https://github.com/nextcloud/all-in-one/pull/5126
- [x] https://github.com/nextcloud/all-in-one/pull/5093
- [x] https://github.com/nextcloud/all-in-one/pull/5117
- [x] https://github.com/nextcloud/all-in-one/pull/5106
- [x] https://github.com/nextcloud/all-in-one/pull/5007 (check regressions below and make smoke test)
- [x] ![image](https://github.com/user-attachments/assets/13dd87ad-7474-416e-83af-2bd2b86fa382)
- [x] ![image](https://github.com/user-attachments/assets/7a545c5d-c577-4882-b41c-a4fad516bb98) (should be fixed with https://github.com/nextcloud/all-in-one/commit/7a3bcc73c6fdce6a12396a3b7768572931504aac and https://github.com/nextcloud/all-in-one/commit/4c162237bfb1ea22ea7cd0b191bf50e12eb4a78d)

### Tasks to do for new release:
- [x] make sure to merge any `Helm Chart Updates` PR before continuing with the list below (https://github.com/nextcloud/all-in-one/pulls?q=is%3Apr+is%3Aopen+helm+)
- [x] increase the version number in https://github.com/nextcloud/all-in-one/blob/main/php/templates/containers.twig#L19
- [x] build new images. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-build-new-containers https://github.com/nextcloud-releases/all-in-one/actions/runs/10703819158
- [x] do a last smoke test using the develop channel (See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-test-things-correctly)
- [x] deploy from develop to beta. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-promote-builds-from-develop-to-beta
- [x] tag a new release [here on github](https://github.com/nextcloud/all-in-one/releases/new) which fits the version number (and use vX.Y.Z as tag and title + `Beta`, use the autogenerated changelog. **Important:** also add the included Nextcloud version manually into the body of the release, e.g. `Nextcloud 26.0.2 is included but new instances can install Nextcloud 27 directly`) and make it a pre release
- [x] rename `next` milestone to the same version number
- [x] create a new milestone that is called `next`
- [x] move all open issues/PRs to that new milestone
- [x] post in all issues and discussions that were fixed/implemented that this is now released with the new beta version and post how to switch to the beta channel (e.g. `This is now released with X.Y.Z Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel`)
- [ ] wait a week and see if new bugs get reported and don't merge any PR into the main branch of this repo in the meantime! https://github.com/nextcloud/all-in-one/issues/5204
- [ ] if not, publish to latest as describe below; if yes simply close this milestone and create a new one that includes the bugfixes and starts from the beginning of this guide
- [ ] deploy from beta to latest. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-promote-builds-from-beta-to-latest
- [ ] Merge the automated `YAML updates` PR if there should  be one (https://github.com/nextcloud/all-in-one/pulls?q=is%3Apr+is%3Aopen+yaml)
- [ ] change the pre-release to be a stable and the latest release and remove `Beta` from the title (and adjust the changelog if multiple Beta version have been pushed in the meantime without a stable release - the changelog must include all changes since the latest stable release)
- [ ] close the old milestone
