### ISSUE TITLE
update existing instances to Nextcloud 30

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#5249]
## Tasks
 
TODO:
- [x] Wait for at least 30.0.2
 
Issues:
- [x] https://github.com/nextcloud/server/issues/48415
- [x] https://github.com/nextcloud/viewer/issues/2567
- [x] https://github.com/nextcloud/server/issues/46777
- [x] https://github.com/nextcloud/server/issues/48475
- [x] https://github.com/nextcloud/server/issues/48468
- [x] https://github.com/nextcloud/server/issues/46976
- [x] https://github.com/nextcloud/server/issues/47286
- [x] https://github.com/nextcloud/server/issues/47642
- [x] https://github.com/nextcloud/server/issues/48012
- [ ] https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue++label%3A30-feedback+

Apps not compatible:
- [x] increase aio version to 30 https://github.com/nextcloud/all-in-one/pull/5547
- [x] [other bundled apps](https://cloud.nextcloud.com/apps/tables/#/table/182)
- [x] [further apps](https://help.nextcloud.com/t/apps-waiting-for-nc-30-support/204064)

Test:
- [x] test new instance?
- [x] check if all included features work
    - [x] ClamAV 
    - [x] Collabora
    - [x] Fulltextsearch 
    - [x] Imaginary (for previews of heic, heif, illustrator, pdf, svg, tiff and webp. Imaginary is currently [incompatible with server-side-encryption](https://github.com/nextcloud/server/issues/34262))
    - [x] Talk
    - [x] talk recording
    - [x] docker-socket-proxy
    - [x] whiteboard
- [x] check admin overview
- [x] check each other overview
- [x] check if nextcloud-aio app works
- [x] https://github.com/nextcloud/all-in-one/pull/5548
- [x] https://github.com/nextcloud/all-in-one/pull/5426
- [x] https://github.com/nextcloud/all-in-one/issues/5063
- [x] https://github.com/nextcloud/all-in-one/pull/4804
- [x] https://github.com/nextcloud/all-in-one/pull/5314
- [x] https://github.com/nextcloud/all-in-one/pull/5549
- [ ] ...

**Comment by daks** [comment]
Looks like 30.0.1 has been released https://github.com/nextcloud/server/releases/tag/v30.0.1

**Comment by szaimen** [comment]
> Looks like 30.0.1 has been released https://github.com/nextcloud/server/releases/tag/v30.0.1

Indeed but we are still waiting for some bugs to get fixed. See the list above. So we are going to wait for 30.0.2

**Comment by A4alli** [comment]
There are many  Security and setup Warnings. Any update on that?

https://pastebin.com/NjdsyzUf

**Comment by szaimen** [comment]
This is now released with v10.0.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

**Comment by Alwaysin** [comment]
@szaimen The bug that you waited for it to be resolved about emails not sent (https://github.com/nextcloud/server/issues/48012) is still there in 30.0.2 under a new issue: https://github.com/nextcloud/server/issues/49133

**Comment by tigernero79** [comment]
news for resolution? thanks
