### ISSUE TITLE
publish new images after recent PRs are merged and tested

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#5583]
### Follow up to https://github.com/nextcloud/all-in-one/issues/5544
(add the most recent ticket for a new release here)

### Tested:
(add PRs below that are potentially breaking and need to be well tested)
- [x] https://github.com/nextcloud/all-in-one/pull/5688
- [x] https://github.com/nextcloud/all-in-one/pull/5590
- [x] https://github.com/nextcloud/all-in-one/pull/5613
- [x] https://github.com/nextcloud/all-in-one/pull/5622
- [x] https://github.com/nextcloud/all-in-one/commit/2ffbeead5372a25b532e6ed4b00b5f0c0b1df106
- [x] https://github.com/nextcloud/all-in-one/pull/5671
- [x] https://github.com/nextcloud/all-in-one/pull/5672
- [x] https://github.com/nextcloud/all-in-one/pull/5673
- [x] ~~https://github.com/nextcloud/all-in-one/pull/5718~~ will be tested by community
- [x] https://github.com/nextcloud/all-in-one/pull/5689
    - [x] apache
    - [x] clamav https://github.com/Cisco-Talos/clamav-docker/blob/0198ab6a7dd5dec2f1d09da7931a8b996103d744/clamav/1.3/alpine/Dockerfile#L124
    - [x] collabora https://github.com/nextcloud/all-in-one/blob/f588b85f0a9712957eb6d7aa9f503374a0682fe4/Containers/collabora/Dockerfile#L20
    - [x] fts https://github.com/nextcloud/all-in-one/blob/f588b85f0a9712957eb6d7aa9f503374a0682fe4/Containers/fulltextsearch/Dockerfile#L21
    - [x] imaginary
    - [x] nextcloud
    - [x] notify-push
    - [x] oo https://github.com/nextcloud/all-in-one/blob/f588b85f0a9712957eb6d7aa9f503374a0682fe4/Containers/onlyoffice/Dockerfile#L7
    - [x] postgres https://github.com/nextcloud/all-in-one/commit/c130cc0c0f47825dd16d81f92c334298647c8140
    - [x] redis
    - [x] talk
    - [x] talk-recording
    - [x] whiteboard
- [x] https://github.com/nextcloud/all-in-one/pull/5705
- [x] https://github.com/nextcloud/all-in-one/commit/247f085d4c5da4699bd4a123b3b0b07a98cf4ac6

### Tasks to do for new release:
- [x] make sure to merge any `Helm Chart Updates` PR before continuing with the list below (https://github.com/nextcloud/all-in-one/pulls?q=is%3Apr+is%3Aopen+helm+)
- [x] increase the version number in https://github.com/nextcloud/all-in-one/blob/main/php/templates/containers.twig#L19
- [x] build new images. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-build-new-containers
- [x] do a last smoke test using the develop channel (See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-test-things-correctly)
- [x] deploy from develop to beta. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-promote-builds-from-develop-to-beta
- [x] tag a new release [here on github](https://github.com/nextcloud/all-in-one/releases/new) which fits the version number (and use vX.Y.Z as tag and title + `Beta`, use the autogenerated changelog. **Important:** also add the included Nextcloud version manually into the body of the release, e.g. `Nextcloud 26.0.2 is included but new instances can install Nextcloud 27 directly`) and make it a pre release
- [x] rename `next` milestone to the same version number
- [x] create a new milestone that is called `next`
- [x] move all open issues/PRs to that new milestone
- [x] post in all issues and discussions that were fixed/implemented that this is now released with the new beta version and post how to switch to the beta channel (e.g. `This is now released with X.Y.Z Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel`)
- [ ] wait a week and see if new bugs get reported and don't merge any PR into the main branch of this repo in the meantime!
- [ ] if not, publish to latest as describe below; if yes simply close this milestone and create a new one that includes the bugfixes and starts from the beginning of this guide
- [ ] deploy from beta to latest. See https://github.com/nextcloud/all-in-one/blob/main/develop.md#how-to-promote-builds-from-beta-to-latest
- [ ] Merge the automated `YAML updates` PR if there should  be one (https://github.com/nextcloud/all-in-one/pulls?q=is%3Apr+is%3Aopen+yaml)
- [ ] change the pre-release to be a stable and the latest release and remove `Beta` from the title (and adjust the changelog if multiple Beta version have been pushed in the meantime without a stable release - the changelog must include all changes since the latest stable release)
- [ ] close the old milestone

**Comment by ne0YT** [comment]
@szaimen so still no stable v30?
