### ISSUE TITLE
publish new images after recent PRs are merged and tested

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#66]
successfully tested:
- [x] #58 (see if it successfully builds)
- [ ] #59 
- [x] #60 works with #92
- [x] #61 
- [x] #62 
- [x] #63 
- [x] #64 
- [x] #77 (see if it successfully builds)
- [x] #89
- [x] #91 (see if it successfully builds)

When done, publish affected images to latest
- [x] nextcloud
- [ ] apache
- [x] borgbackup
- [x] all-in-one
- [x] postgresql
- [x] redis
